// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxwCv1PJdbHxZ21mhcnKmV7Niw3NzfRC0',
    appId: '1:698696370142:web:86c896f882a680075f7f4f',
    messagingSenderId: '698696370142',
    projectId: 'authentication-fb98c',
    authDomain: 'authentication-fb98c.firebaseapp.com',
    storageBucket: 'authentication-fb98c.appspot.com',
    measurementId: 'G-MY6S3R1HQ7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXKIIVJb46H8C_eap0GeJCkfcpVmx_I3A',
    appId: '1:698696370142:android:c828240ea932df5e5f7f4f',
    messagingSenderId: '698696370142',
    projectId: 'authentication-fb98c',
    storageBucket: 'authentication-fb98c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOpQvnBGFNlooQpbly0ap5QM9WP7zav1E',
    appId: '1:698696370142:ios:7ed76cdb60773d9a5f7f4f',
    messagingSenderId: '698696370142',
    projectId: 'authentication-fb98c',
    storageBucket: 'authentication-fb98c.appspot.com',
    iosClientId: '698696370142-ffuoc4gm09on4adenqce19i3vv1i8gpu.apps.googleusercontent.com',
    iosBundleId: 'com.example.minggu11',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAOpQvnBGFNlooQpbly0ap5QM9WP7zav1E',
    appId: '1:698696370142:ios:7ed76cdb60773d9a5f7f4f',
    messagingSenderId: '698696370142',
    projectId: 'authentication-fb98c',
    storageBucket: 'authentication-fb98c.appspot.com',
    iosClientId: '698696370142-ffuoc4gm09on4adenqce19i3vv1i8gpu.apps.googleusercontent.com',
    iosBundleId: 'com.example.minggu11',
  );
}
